default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
        exclude: factories.py
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: README.md
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ['--skip-string-normalization']
        exclude: ^migrations/
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        exclude: ^migrations/
