version: '3' 

services: 
  web: 
    build: . 
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver  0.0.0.0:8000" 
    container_name: inventory-management
    volumes: 
      - .:/code 
    ports: 
      - "80:8000"
